name: celest_backend
description: The Celest backend for liberpass.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  celest: ^0.3.0
  celest_core: ^0.3.0
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
celest:
  project:
    id: project_01htmk5m82etyfs7yyaawwx42a
